const getCategories = ($: TemplateStrBuilder): string[] => [
	$`Categoría`,
	$`Alimentos y Bebidas`,
	$`Animales y Mascotas`,
	$`Arte`,
	$`Aseguradoras`,
	$`Automotor`,
	$`Bar`,
	$`Bebés y Maternidad`,
	$`Belleza y Cuidado Personal`,
	$`Cafetería`,
	$`Carnicería y Pescadería`,
	$`Carpintería`,
	$`Celulares y Telefonía`,
	$`Cerrajería y Ferretería`,
	$`Cine`,
	$`Coaching`,
	$`Computación e Informática`,
	$`Concesionario`,
	$`Delivery`,
	$`Dentista`,
	$`Deportes y Fitness`,
	$`Diseño gráfico`,
	$`Educación`,
	$`Electrodomésticos`,
	$`Electrónica, Audio y Video`,
	$`Entretenimiento`,
	$`Eventos`,
	$`Farmacia`,
	$`Finanzas`,
	$`Flete y Mudanzas`,
	$`Fotografía y Video`,
	$`Gimnasio`,
	$`Herramientas y Construcción`,
	$`Hogar y Muebles`,
	$`Hospedajes`,
	$`Hostelería`,
	$`Imprenta`,
	$`Inmobiliaria`,
	$`Juegos y Juguetes`,
	$`Kiosco`,
	$`Lavandería`,
	$`Libros, Revistas y Comics`,
	$`Marca personal`,
	$`Marketing y publicidad`,
	$`Médico`,
	$`Música`,
	$`Óptica`,
	$`Otros`,
	$`Panadería y Repostería`,
	$`Películas`,
	$`Redes sociales`,
	$`Relojes y Joyas`,
	$`Restaurante`,
	$`Ropa Interior y Accesorios`,
	$`Ropa de mujer, hombre y niño`,
	$`Salud y Equipamiento Médico`,
	$`Servicio de mensajería`,
	$`Servicio Técnico`,
	$`Servicios Profesionales`,
	$`Supermercado`,
	$`Taxi`,
	$`Tecnología`,
	$`Tienda Online`,
	$`Transporte`,
	$`Universidades`,
	$`Vestuario y Calzado`,
	$`Veterinaria`,
	$`Viajes y Turismo`,
]

export default getCategories
